function output = scrambler(len,init_state)
% data scrambler
% len: length of sequence generated by the scrambler
% init_state: row vector of initial state of scrambler
% output: row vector of sequence generated by the scrambler

output = zeros(1,len);

if length(init_state) ~= 7
    error('invalid initial state of srambler.');
else
    shift_reg = init_state;
end;

for i = 1:len
    output(i) = rem(shift_reg(4) + shift_reg(7),2);
    shift_reg = [output(i),shift_reg(1:6)];
end;
