#===- ./Makefile -------------------------------------------*- Makefile -*--===#
# 
#        
#
# 
# @Author: Sheng Zhou, AutoESL Design Technologies, Inc. 
#
#===------------------------------------------------------------------------===#

LEVEL = ../../../..

include $(LEVEL)/Makefile.common

LEVEL = ../..

CURR_DIR = etc

include $(LEVEL)/Makefile.scan
